---

- dynamic_defaults:
    hostvars: '{{ hostvars[inventory_hostname] }}'
    defaults: '{{ buildah_dynamic_defaults }}'
    must_match: yes
  tags: [buildah, always]

- block:
    - include_tasks: setup-repository-{{ ansible_pkg_mgr }}.yml

    - name: Install buildah packages
      package:
        name: '{{ buildah_packages }}'
        state: present
  become: '{{ do_become }}'
  tags: [buildah, packages]

- block:
    - name: Configure Buildah registries
      template:
        src: '{{ buildah_registries_config_file }}'
        dest: /etc/containers/registries.conf
        mode: 0644
      notify: containers registries changed

    - name: Create directories for Buildah registries certificates
      file:
        path: '/etc/containers/certs.d/{{ item.host }}:{{ item.port|int }}'
        state: "{{ buildah_registries_certificates_states[item.state|default('present')] }}"
        mode: 0755
      loop: '{{ buildah_registries_certificates }}'
      loop_control:
        label: '{{ item.host }}:{{ item.port|int }}'

    # https://www.mankier.com/5/containers-certs.d
    - name: Setup Buildah registries certificates
      copy:
        content: '{{ item.0[item.1.key] }}'
        dest: '/etc/containers/certs.d/{{ item.0.host }}:{{ item.0.port|int }}/{{ item.1.path }}'
        mode: 0644
      diff: not item.1.hidden
      loop: '{{ buildah_registries_certificates|product(buildah_registries_certificates_files)|list }}'
      loop_control:
        label: '{{ item.0.host }}:{{ item.0.port|int }} -> {{ item.1.key }}'
      when: item.0.state|default('present') == 'present' and item.1.key in item.0

    - name: Configure Buildah storage
      template:
        src: '{{ buildah_storage_config_file }}'
        dest: /etc/containers/storage.conf
        mode: 0644
      notify: containers storage changed
  become: '{{ do_become }}'
  tags: [buildah, config]
